let products = [
  {
    id: 1,
    img: "images/product1.jpg",
    title: "Adidas T-Shirt",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing",
    price: "375",
  },
  {
    id: 2,
    img: "images/product2.jpg",
    title: "Adidas Airpods",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing",
    price: "1999",
  },
  {
    id: 3,
    img: "images/product3.jpg",
    title: "Adidas Hoodie",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing",
    price: "550",
  },
  {
    id: 4,
    img: "images/product4.jpg",
    title: "Adidas Bottle",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing",
    price: "240",
  },
  {
    id: 5,
    img: "images/product5.jpg",
    title: "Adidas Eyeglasses",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing",
    price: "150",
  },
  {
    id: 6,
    img: "images/product6.jpg",
    title: "Adidas Cap",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing",
    price: "250",
  },
  {
    id: 7,
    img: "images/product7.jpg",
    title: "Adidas Backbag",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing",
    price: "350",
  },
  {
    id: 8,
    img: "images/product8.jpg",
    title: "Adidas Shoes",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing",
    price: "450",
  },
];
